### ISSUE TITLE
PolygonalFace

### ISSUE THREAD

**Issue by petrasvestartas** [DesignEngrLab/TVGL#18]
Hi,

I am new user of TVGL.
I am very interested in this rich library, however I am interested in particular subject,

Is it possible to get very simple example how to create 3d polygon that has faces with more than 3 or 4 vertices?

Thank you

**Comment by micampbell** [comment]
Thanks for your interest. Here's the simplest shape that can be made:

            var vertices = new[]
            {
                    new[] {0.0, 0.0, 0.0},
                    new[] {1.0, 0.0, 0.0},
                    new[] {0.0, 1.0, 0.0},
                    new[] {0.0, 0.0, 1.0}
                };
            var faceIndices = new[]
            {
                    new[] {1, 0, 2},
                    new[] {2, 0, 3},
                    new[] {3, 0, 1},
                    new[] {1, 2, 3}
                };
            ;

            var ts = new TessellatedSolid(vertices, faceIndices, null);

            Presenter.ShowAndHang(ts);


There are several TessellatedSolid constructors, which are mostly suited for reading in different file. But this one can easily be used directly.

**Comment by petrasvestartas** [comment]
Thank you very much for a reply.

When working with this library is it possible to have polygon faces that consists from more than 4 vertices?
I used to work with mesh that are either quads or triangles, but I would really like to work with this kind of 3d polygons:
https://www.blender.org/manual/de/_images/bmesh_make_face_edges_ngon_simple_after.png

These libraries are usually 2d, but I was wondering is it possible to construct an object like this using your lirbrary:
https://openclipart.org/image/2400px/svg_to_png/177468/1366937053.png

The purpose of this is to simply have adjacency map of 3d polygons (not quads or triangle meshes).

Thank you,
Petras

**Comment by micampbell** [comment]
yep. The face indices can take polygons. It will triangulate these in the constructor. For example:

            var vertices = new[]
            {
                    new[] {0.0, 0.0, 0.0},
                    new[] {1.0, 0.0, 0.0},
                    new[] {0.0, 1.0, 0.0},
                    new[] {1.0, 1.0, 0.0},
                    new[] {0.0, 0.0, 1.0}
                };
            var faceIndices = new[]
            {
                    new[] {1, 0, 2, 3}, // face with four vertices
                    new[] {2, 0, 4},
                    new[] {4, 0, 1},
                    new[] {1, 3, 4},
                    new[] {4, 3, 2}
                };
            ;

            var ts = new TessellatedSolid(vertices, faceIndices, null);
            Console.WriteLine(ts.NumberOfFaces);

This prints that the number of faces since the first one is separated into two triangular faces.

**Comment by petrasvestartas** [comment]
Very nice, that is what I am looking for. 

Is there is a documentation for your library and more example like this? 
Not necessary with polygons.

I would really like to implement this library in my workflow:)

**Comment by micampbell** [comment]
There needs to be! Right now, I occasionally re-create the help files...http://designengrlab.github.io/TVGL/help/index.html
but these are hard to learn from. Currently, the users/developers all sit in the same vicinity, so we talk through the stuff in-person. But this doesn't mean you're not welcome here! We would really like to see people adopt it, so please keep up with your questions/posts. We'll be sure to respond as quickly as possible.

**Comment by petrasvestartas** [comment]
Will do:) Thank you :)

**Comment by petrasvestartas** [comment]
Hi,

I tried your example. When I print number of faces:
 Console.WriteLine(ts.NumberOfFaces);
I get "6" 

But is it possible to work with polygons? So that I would have only 1 face with 5 vertices.
I know that for shading ngon have to triangulated. But I need to work on those polylines only.

For instance I have two 3d polylines, that share one edge. And what I would like to get its adjacency of each other. More simple two pentagons that share one edge. How to get index of neighbour polyline, not triangle face.

**Comment by petrasvestartas** [comment]
I am only searching for data-structure that works like meshes but with n-gons. I do not need any shading just methods to deal with those outlines and ability to know their neighbours. 
So that one face is actual polyline.

Like this:

![daces](https://cloud.githubusercontent.com/assets/18013985/21594908/803c2758-d128-11e6-92c0-e45d12a66c4e.png)


![faces](https://cloud.githubusercontent.com/assets/18013985/21594888/43176d88-d128-11e6-868f-8798283fc582.png)

**Comment by micampbell** [comment]
Okay, this may or may not be helpful. Within our tessellated solid class, we do store "Primitives". These are groups of faces that represent a larger flat region (or a cylinder, sphere, etc).
I think we had this at one point, but I made some changes just now to add it back in.
Now when you load my simple pyramid, the tessellated solid includes one primitive, which is the square Flat region on the bottom.


            var vertices = new[]
           {
                new[] {0.0, 0.0, 0.0},
                new[] {1.0, 0.0, 0.0},
                new[] {0.0, 1.0, 0.0},
                new[] {1.0, 1.0, 0.0},
                new[] {0.0, 0.0, 1.0}
            };
            var faceIndices = new[]
            {
                new[] {1, 0, 2, 3}, // face with four vertices
                new[] {2, 0, 4},
                new[] {4, 0, 1},
                new[] {1, 3, 4},
                new[] {4, 3, 2}
            };
            
            var ts = new TessellatedSolid(vertices, faceIndices, null);
            var outerEdges = ts.Primitives[0].OuterEdges;
            Console.WriteLine(outerEdges.Count);


Note that this prints 4. Within the primitives, the inner and outer edges are stored. However, this is a one-way reference as the edges are between triangular faces, so you have to write a bit of code to get from one primitive flat region to the next.

**Comment by petrasvestartas** [comment]
If I am correct the procedure as follows:
1. Vertices array
2. Faces array
3. Construct TesselatedSolid from vertices and faces.
4. OuterEdges gets naked edges of the mesh. Primitive has an index of 0.

Question:
1. How does the code look like if there are more than 1 primitive within tesselated solid?

 2."These are groups of faces that represent a larger flat region "
 Is it possible to operate on non flat primitives?

3. Does the primitive "knows" that it has a neighbour of another primitive?

Thank you.

**Comment by petrasvestartas** [comment]
May I get answer to my last question?:)

**Comment by micampbell** [comment]
Sorry for the delay. The Primitives is a List of type SurfacePrimitive. This may contain cylinders, or spheres, or cones, or tori, or flats. These are usually created by calling the static function, Primitive_Classification.Run(TessellatedSolid ts). 
However, if the original shape data (often provided via files or - in this case - provided programmatically) contains polygons with more than 3 sides, then they are still made into triangles, but a Flat Surface Primitive is created that references all the triangles in the polygon. In Flat, one can find these faces as well as lists for the InnerEdges and the OuterEdges.
Since there was only one polygon with more than 3 sides in the data, then there is only one element in the list Primitives - hence why the code reference Primitives[0].
So, if you load in a dodecahedron (like your figure) or an icasohedron, then you would get 12 or 20 Flats in Primitives. You could access the outeredges of each of these which would have reference data to the next region, but unfortunately Edges only reference back to their triangular faces - not these primitives. A special "look-up" function would need to be created. It won't be hard to make, but it could be slow for very large models.
