### ISSUE TITLE
Tessellated solid "transfer" method

### ISSUE THREAD

**Issue by mvelayati** [DesignEngrLab/TVGL#19]
Can we add a transfer method  to the Tessellated class in order to simply move the solid to a new location?

**Comment by micampbell** [comment]
You can use the Transform method which is a non-static method under TessellatedSolid. Only provide values for the last column of the 4x4 matrix.
|   1   0   0   tx   |
|   0   1   0   ty   |
|   0   0   1   tz   |
|   0   0   0   1    |
