### ISSUE TITLE
Missing oneOverG and oneOverH in MiscFunctions

### ISSUE THREAD

**Issue by Luc-BOLOGNA** [DesignEngrLab/TVGL#64]
Hello :)
I want to try your code but I can't build it.

I've cloned from master. Then when I build I've issue in the MiscFunctions.cs file. See
![image](https://github.com/user-attachments/assets/97618d93-a4c9-4815-8baf-d00951fb57fc)

BR,

**Comment by micampbell** [comment]
I believe I've fixed it now. So sorry for leaving it in this state.

________________________________
From: Luc BOLOGNA ***@***.***>
Sent: Tuesday, August 20, 2024 6:54 AM
To: DesignEngrLab/TVGL ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [DesignEngrLab/TVGL] Missing oneOverG and oneOverH in MiscFunctions (Issue #64)


[This email originated from outside of OSU. Use caution with links and attachments.]

Hello :)
I want to try your code but I can't build it.

I've cloned from master. Then when I build I've issue in the MiscFunctions.cs file. See
image.png (view on web)<https://github.com/user-attachments/assets/97618d93-a4c9-4815-8baf-d00951fb57fc>

BR,
